[package]
name = "orders"
version = "0.1.0"
authors = ["kevin <kevin.janada@gmail.com>"]
edition = "2018"
description = ''
homepage = ''
license = 'Unlicense'
repository = ''

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
serde = { version = "1.0.101", optional = true }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
pallet-timestamp = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }
services = { path = '../services', default-features = false }
traits-services = { path = '../../traits/services', default-features = false }
traits-genetic-testing = { path = '../../traits/genetic-testing', default-features = false }
traits-user-profile = { path = '../../traits/user-profile', default-features = false }
traits-order = { path = '../../traits/order', default-features = false }
chrono = { default-features = false, version = '0.4' }

[dev-dependencies]
sp-core = { default-features = false, version = '3.0.0' }
sp-io = { default-features = false, version = '3.0.0' }
sp-runtime = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-std/std',
    'sp-core/std',
    'pallet-timestamp/std',
    'services/std',
    'chrono/std',
    'traits-services/std',
    'traits-genetic-testing/std',
    'traits-user-profile/std',
    'traits-order/std',
]
